version: "3"
services:

  redis:
    image: redis:5-alpine
    volumes:
      - ./redis.volatile.conf:/etc/redis/redis.conf:ro
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
