const rawValidators = [
	{
		name: 'xgblycabvgjzmbxvgsfz',
		totalStake: '1000000000',
		selfStake: '0',
		validatorWeight: '0',
		address: 'lskedaybfvookeu6oc5fdxss7ekj9jjsngro8jqc7',
		lastGeneratedHeight: 18031,
		status: 'ineligible',
		isBanned: false,
		reportMisbehaviorHeights: [],
		punishmentPeriods: [],
		consecutiveMissedBlocks: 0,
		commission: 114,
		lastCommissionIncreaseHeight: 18031,
		sharingCoefficients: [],
		rank: 270,
		generatedBlocks: 0,
		totalCommission: '0',
		totalSelfStakeRewards: '0',
		earnedRewards: '0',
	},
	{
		name: 'cchpavxrjiwwrdgprlld',
		totalStake: '1000000000',
		selfStake: '0',
		validatorWeight: '0',
		address: 'lsku6jqx9gtnnjx5fnzahobnqneuhmofjmm7wozm4',
		lastGeneratedHeight: 18031,
		status: 'ineligible',
		isBanned: false,
		reportMisbehaviorHeights: [],
		punishmentPeriods: [],
		consecutiveMissedBlocks: 0,
		commission: 145,
		lastCommissionIncreaseHeight: 18031,
		sharingCoefficients: [],
		rank: 182,
		generatedBlocks: 0,
		totalCommission: '0',
		totalSelfStakeRewards: '0',
		earnedRewards: '0',
	},
	{
		name: 'rgfbrwgkdifyrvrxqkgz',
		totalStake: '1000000000',
		selfStake: '0',
		validatorWeight: '0',
		address: 'lsk5nemreyqpoj6oqhkfcn4hs8sq27rhfobz9c7tc',
		lastGeneratedHeight: 17640,
		status: 'ineligible',
		isBanned: false,
		reportMisbehaviorHeights: [],
		punishmentPeriods: [],
		consecutiveMissedBlocks: 0,
		commission: 181,
		lastCommissionIncreaseHeight: 17640,
		sharingCoefficients: [],
		rank: 138,
		generatedBlocks: 0,
		totalCommission: '0',
		totalSelfStakeRewards: '0',
		earnedRewards: '0',
	},
];

module.exports = {
	rawValidators,
};
