version: '3'
services:
  lisk-core:
    image: lisk/core:3.0.0-beta.4
    volumes:
      - ./lisk-core/snapshots/:/tmp/snapshots
      - ./lisk-core/entrypoint.sh:/entrypoint.sh
    ports:
      - 4000
      - 5001
    networks:
      - local_lisk_core
    restart: always
    entrypoint: ['sh', '/entrypoint.sh']
    environment:
      - LISK_API_PUBLIC=true

  core:
    networks:
      - local_lisk_core
    environment:
      - LISK_CORE_HTTP=http://lisk-core:4000
      - LISK_CORE_WS=ws://lisk-core:5001

networks:
  local_lisk_core:
