version: '3.3'
services:
  mysql-primary:
    image: mariadb:10
    container_name: mysql-primary
    command: mysqld
    volumes:
      - ../../docker/mariadb/primary/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - mysql-primary-data:/var/lib/mysql
      - ../../docker/mariadb/primary/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - services_network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=lisk
      - MYSQL_PASSWORD=password
    ports:
      - '127.0.0.1:3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-hlocalhost', '-ppassword']

  mysql-read-replica:
    image: mariadb:10
    depends_on:
      mysql-primary:
        condition: service_healthy
    command: mysqld
    volumes:
      - ../../docker/mariadb/read/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ../../docker/mariadb/read/init:/docker-entrypoint-initdb.d
    restart: always
    expose:
      - '3306'
    networks:
      - services_network
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-hlocalhost', '-ppassword']

  mysql-read-replica-haproxy:
    image: nginx:latest
    depends_on:
      mysql-read-replica:
        condition: service_healthy
    volumes:
      - ../../docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '127.0.0.1:3307:3307'
    networks:
      - services_network
    healthcheck:
      test: ['CMD', 'service', 'nginx', 'status']

networks:
  services_network:

volumes:
  mysql-primary-data:
