# Base file, do not modifiy.
# Make changes in docker-compose.override.yml instead.
# See https://docs.docker.com/compose/extends/#example-use-case
version: '3.3'
services:

  mariadb:
    image: mariadb:10.6
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-healthcheck.sh:/healthcheck.sh
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: lisk
      MARIADB_USER: lisk
      MARIADB_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ['CMD', 'bash', '/healthcheck.sh']
      interval: 1m
      timeout: 5s

volumes:
  db-data:
