version: "3"
services:

  redis_common:
    image: redis:5-alpine
    volumes:
      - ./redis/redis.volatile.conf:/etc/redis/redis.conf:ro
    networks:
      - services_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping

networks:
  services_network:
