module.exports = {
	account: {
		address: 'string',
		confirmed_balance: 'number',
		n_tx: 'number',
		unconfirmed_balance: 'number',
	},
	txsEnvelop: {
		block: 'object',
		confirmations: 'number',
		feeSatoshi: 'number',
		height: 'number',
		inputTotalSatoshi: 'number',
		outputTotalSatoshi: 'number',
		timestamp: 'number',
		tx: 'object',
		tx_raw: 'number',
	},
	txs: {
		block: {
			bits: 'number',
			block_height: 'number',
			merkle_root: 'string',
			nonce: 'number',
			prev_block_hash: 'string',
			timestamp: 'number',
			version: 'number',
		},
		confirmations: 'number',
		feeSatoshi: 'number',
		height: 'number',
		inputTotalSatoshi: 'number',
		outputTotalSatoshi: 'number',
		timestamp: 'number',
		tx: {
			inputs: [
				{
					n: 'number',
					script: 'string',
					sequence: 'number',
					txDetail: 'object',
					txid: 'string',
				},
			],
			locktime: 'number',
			outputs: [
				{
					n: 'number',
					satoshi: 'number',
					scriptPubKey: 'object',
					value: 'string',
				},
			],
			txid: 'string',
			version: 'number',
		},
		tx_raw: 'string',
	},
	txsTx: {
		inputs: 'array',
		locktime: 'number',
		outputs: 'array',
		txid: 'string',
		version: 'number',
	},
	txDetail: {
		n: 'number',
		satoshi: 'number',
		scriptPubKey: 'object',
		value: 'string',
	},
	scriptPubKey: {
		addresses: 'array',
		asm: 'string',
		hex: 'string',
	},
	txEnvelop: {
		confirmations: 'number',
		feeSatoshi: 'number',
		height: 'number',
		inputTotalSatoshi: 'number',
		outputTotalSatoshi: 'number',
		timestamp: 'number',
		tx: 'object',
		tx_raw: 'number',
	},
	tx: {
		confirmations: 'number',
		feeSatoshi: 'number',
		height: 'number',
		inputTotalSatoshi: 'number',
		outputTotalSatoshi: 'number',
		timestamp: 'number',
		tx: {
			inputs: [
				{
					n: 'number',
					script: 'string',
					sequence: 'number',
					txDetail: 'object',
					txid: 'string',
				},
			],
			locktime: 'number',
			outputs: [
				{
					n: 'number',
					satoshi: 'number',
					scriptPubKey: 'object',
					value: 'string',
				},
			],
			txid: 'string',
			version: 'number',
		},
		tx_raw: 'number',
	},
	utxo: {
		height: 'number',
		tx_hash: 'string',
		tx_pos: 'number',
		value: 'number',
	},
};
