= Configuration with Docker
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
:description: Describes how to configure Lisk Service with Docker.
:toc:
:imagesdir: ../assets/images
:page-previous: /lisk-service/setup/docker.html
:page-previous-title: Installation with Docker
:page-next: /lisk-service/management/docker.html
:page-next-title: Docker commands
:url_references_config: configuration/index.adoc
:url_github_env: https://github.com/LiskHQ/lisk-service/blob/development/docker/example.env
:url_docker_commands: management/docker.adoc

On this page, we discuss how to customize the docker installation of Lisk Service.


== Configuring Lisk Service
The Docker installation of Lisk Service takes all of its configuration from an `example.env` file, which is located in the `lisk-service` directory.

To customize the docker installation, copy the example configuration file to any `.env` file.

.Working directory: ./lisk-service/
[source,bash]
----
cp docker/example.env .env
----

You can edit the newly copied `.env` file to customize configurations accordingly.
All the Lisk Service related configurations have already been explained on the xref:{url_references_config}[Configuration reference] page.

== Default example.env

The default {url_github_env}[example.env] file can be seen on the GitHub repository.

Additional commands for managing Lisk Service with docker are described on the xref:{url_docker_commands}[] page.