= Configuration with Docker
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>
:description: Describes how to configure Lisk Service with Docker.
:toc:
:imagesdir: ../assets/images
:page-previous: /lisk-service/setup/docker.html
:page-previous-title: Installation with Docker
:page-next: /lisk-service/management/docker.html
:page-next-title: Docker commands
:url_references_config: configuration/index.adoc
:url_github_env: https://github.com/LiskHQ/lisk-service/blob/development/docker/example.env

On this page, we discuss how to customize the docker installation of Lisk Service.


== Configuring Lisk Service
The Docker installation of Lisk Service takes all of its configuration from an `example.env` file, which is located in the `lisk-service` directory.

To customize the docker installation, copy the example configuration file to any `.env` file.

.Working directory: ./lisk-service/
[source,bash]
----
cp docker/example.env .env
----

You can edit the newly copied `.env` file to customize configurations accordingly.
All the Lisk Service related configurations have already been explained on the xref:{url_references_config}[Configuration reference] page.

== Default example.env

The default example.env file can be seen on the GitHub repository. 

To show the current configuration of Lisk Service, execute the following command:

.lisk-service/
[source,bash]
----
make print-config
----

.Result for the default config, which will connect Lisk Service to a locally running Lisk Core node.
[source,yaml]
----
docker-compose config
networks:
  core_network: {}
  gateway_network: {}
  market_network: {}
  newsfeed_network: {}
  services_network: {}
services:
  core:
    depends_on:
      mysql_core:
        condition: service_started
      redis_common:
        condition: service_started
      redis_core_persistent:
        condition: service_started
      redis_core_volatile:
        condition: service_started
    environment:
      ENABLE_FEE_ESTIMATOR_FULL: "false"
      ENABLE_FEE_ESTIMATOR_QUICK: "true"
      ENABLE_TRANSACTION_STATS: "true"
      GEOIP_JSON: ''
      INDEX_N_BLOCKS: '0'
      LISK_CORE_WS: ws://host.docker.internal:8080
      LISK_STATIC: https://static-data.lisk.com
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_CORE_MYSQL: mysql://lisk:password@mysql_core:3306/lisk
      SERVICE_CORE_REDIS: redis://redis_core_persistent:6379/0
      SERVICE_CORE_REDIS_VOLATILE: redis://redis_core_volatile:6379/0
      TRANSACTION_STATS_HISTORY_LENGTH_DAYS: '366'
    extra_hosts:
    - host.docker.internal:host-gateway
    image: lisk/service_core
    networks:
      core_network: null
      services_network: null
    restart: always
  gateway:
    depends_on:
      core:
        condition: service_started
      redis_gateway_volatile:
        condition: service_started
    environment:
      ENABLE_HTTP_API: http-status,http-version2
      ENABLE_HTTP_CACHE_CONTROL: "false"
      ENABLE_WS_API: blockchain,rpc-v2
      ENABLE_WS_RATELIMIT: "false"
      HTTP_CACHE_CONTROL_DIRECTIVES: public,max-age=10
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_GATEWAY_REDIS_VOLATILE: redis://redis_gateway_volatile:6379/0
      WS_RATELIMIT_DURATION: '1'
      WS_RATELIMIT_POINTS: '5'
    healthcheck:
      test: curl --fail http://gateway:9901/api/v2/transactions
    image: lisk/service_gateway
    networks:
      gateway_network: null
      services_network: null
    ports:
    - published: 9901
      target: 9901
    restart: always
  market:
    depends_on:
      redis_common:
        condition: service_started
      redis_market:
        condition: service_started
    environment:
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_MARKET_FIAT_CURRENCIES: USD
      SERVICE_MARKET_REDIS: redis://redis_market:6379/0
      SERVICE_MARKET_TARGET_PAIRS: LSK_BTC,LSK_USD
    image: lisk/service_market
    networks:
      market_network: null
      services_network: null
    restart: always
  mysql_core:
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lisk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: lisk
    healthcheck:
      retries: 10
      test:
      - CMD
      - mysqladmin
      - ping
      - -hlocalhost
      - -ppassword
      timeout: 20s
    image: mysql:8
    networks:
      core_network: null
    restart: always
    volumes:
    - mysql-data-core:/var/lib/mysql:rw
  mysql_newsfeed:
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lisk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: lisk
    healthcheck:
      retries: 10
      test:
      - CMD
      - mysqladmin
      - ping
      - -hlocalhost
      - -ppassword
      timeout: 20s
    image: mysql:8
    networks:
      newsfeed_network: null
    restart: always
    volumes:
    - mysql-data-newsfeed:/var/lib/mysql:rw
  newsfeed:
    depends_on:
      mysql_newsfeed:
        condition: service_started
      redis_common:
        condition: service_started
    environment:
      SERVICE_BROKER: redis://redis_common:6379/0
      SERVICE_NEWSFEED_MYSQL: mysql://lisk:password@mysql_newsfeed:3306/lisk
      TWITTER_ACCESS_TOKEN_KEY: ''
      TWITTER_ACCESS_TOKEN_SECRET: ''
      TWITTER_CONSUMER_KEY: ''
      TWITTER_CONSUMER_SECRET: ''
    image: lisk/service_newsfeed
    networks:
      newsfeed_network: null
      services_network: null
    restart: always
  redis_common:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      services_network: null
    restart: always
    volumes:
    - /Users/mona/git/lisk-service/docker/redis.volatile.conf:/etc/redis/redis.conf:ro
  redis_core_persistent:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      core_network: null
    restart: always
    volumes:
    - /Users/mona/git/lisk-service/docker/redis.persistent.conf:/etc/redis/redis.conf:ro
    - redis-data-core:/data:rw
  redis_core_volatile:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      core_network: null
    restart: always
    volumes:
    - /Users/mona/git/lisk-service/docker/redis.volatile.conf:/etc/redis/redis.conf:ro
  redis_gateway_volatile:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      gateway_network: null
    restart: always
    volumes:
    - /Users/mona/git/lisk-service/docker/redis.volatile.conf:/etc/redis/redis.conf:ro
  redis_market:
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
    image: redis:5-alpine
    networks:
      market_network: null
    restart: always
    volumes:
    - /Users/mona/git/lisk-service/docker/redis.persistent.conf:/etc/redis/redis.conf:ro
    - redis-data-market:/data:rw
version: '3'
volumes:
  mysql-data-core: {}
  mysql-data-newsfeed: {}
  redis-data-core: {}
  redis-data-market: {}
----

