= Lisk Service Configuration Reference
Muhammad Talha <muhammad.talha@lightcurve.io>
:toc:

On the Introduction to Lisk Service page, we have discussed the various microservices that combine together to form Lisk Service. On this page, we will thoroughly discuss the configuration options available for Lisk Service.

// * <<gateway>>
// * <<connector>>
// * <<coordinator>>
// * <<indexer>>
// * <<blockchain-application-registry>>
// * <<fee-estimator>>
// * <<transaction-statistics>>
// * <<market>>
// * <<export>>

== Default configurations
By default, a Lisk Service installation will have a `ecosystem.config.js` file with all the default configurations.

.`ecosystem.config.js`
[%collapsible]
====
[source,javascript]
----
module.exports = {
	apps: [
		{
			name: 'lisk-service-gateway',
			script: 'app.js',
			cwd: './services/gateway',
			pid_file: './pids/service_gateway.pid',
			out_file: './logs/service_gateway.log',
			error_file: './logs/service_gateway.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '300M',
			autorestart: true,
			env: {
				PORT: '9901',
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_GATEWAY_REDIS_VOLATILE: 'redis://localhost:6379/5',
				ENABLE_HTTP_API: 'http-status,http-version3,http-exports',
				ENABLE_WS_API: 'blockchain,rpc-v3',
				GATEWAY_DEPENDENCIES: 'indexer,connector',
				WS_RATE_LIMIT_ENABLE: 'false',
				WS_RATE_LIMIT_CONNECTIONS: 5,
				WS_RATE_LIMIT_DURATION: 1, // in seconds
				ENABLE_REQUEST_CACHING: 'true',
				JSON_RPC_STRICT_MODE: 'false',
				HTTP_RATE_LIMIT_ENABLE: 'false',
				HTTP_RATE_LIMIT_CONNECTIONS: 200,
				HTTP_RATE_LIMIT_WINDOW: 10, // in seconds
				HTTP_CACHE_CONTROL_DIRECTIVES: 'public, max-age=10',
				ENABLE_HTTP_CACHE_CONTROL: 'true',
			},
		},
		{
			name: 'lisk-service-blockchain-app-registry',
			script: 'app.js',
			cwd: './services/blockchain-app-registry',
			pid_file: './pids/service_blockchain_app_registry.pid',
			out_file: './logs/service_blockchain_app_registry.log',
			error_file: './logs/service_blockchain_app_registry.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '150M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_APP_REGISTRY_MYSQL: 'mysql://lisk:password@localhost:3306/lisk',
				ENABLE_REBUILD_INDEX_AT_INIT: 'false',
			},
		},
		{
			name: 'lisk-service-blockchain-connector',
			script: 'app.js',
			cwd: './services/blockchain-connector',
			pid_file: './pids/service_blockchain_connector.pid',
			out_file: './logs/service_blockchain_connector.log',
			error_file: './logs/service_blockchain_connector.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '150M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				LISK_APP_WS: 'ws://localhost:7887',
				GEOIP_JSON: 'https://geoip.lisk.com/json',
				USE_LISK_IPC_CLIENT: 'true',
				// LISK_APP_DATA_PATH: '~/.lisk/lisk-core',
				// ENABLE_TESTING_MODE: 'false',
			},
		},
		{
			name: 'lisk-service-blockchain-indexer',
			script: 'app.js',
			cwd: './services/blockchain-indexer',
			pid_file: './pids/service_blockchain_indexer.pid',
			out_file: './logs/service_blockchain_indexer.log',
			error_file: './logs/service_blockchain_indexer.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '500M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_INDEXER_CACHE_REDIS: 'redis://localhost:6379/1',
				SERVICE_INDEXER_REDIS_VOLATILE: 'redis://localhost:6379/2',
				SERVICE_MESSAGE_QUEUE_REDIS: 'redis://localhost:6379/3',
				SERVICE_INDEXER_MYSQL: 'mysql://lisk:password@localhost:3306/lisk',
				ENABLE_DATA_RETRIEVAL_MODE: 'true',
				ENABLE_INDEXING_MODE: 'true',
				ENABLE_PERSIST_EVENTS: 'false',
			},
		},
		{
			name: 'lisk-service-blockchain-coordinator',
			script: 'app.js',
			cwd: './services/blockchain-coordinator',
			pid_file: './pids/service_blockchain_coordinator.pid',
			out_file: './logs/service_blockchain_coordinator.log',
			error_file: './logs/service_blockchain_coordinator.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '300M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_MESSAGE_QUEUE_REDIS: 'redis://localhost:6379/3',
			},
		},
		{
			name: 'lisk-service-fee-estimator',
			script: 'app.js',
			cwd: './services/fee-estimator',
			pid_file: './pids/service_fee_estimator.pid',
			out_file: './logs/service_fee_estimator.log',
			error_file: './logs/service_fee_estimator.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '300M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_FEE_ESTIMATOR_CACHE: 'redis://localhost:6379/1',
				ENABLE_FEE_ESTIMATOR_QUICK: 'true',
				ENABLE_FEE_ESTIMATOR_FULL: 'false',
			},
		},
		{
			name: 'lisk-service-transaction-statistics',
			script: 'app.js',
			cwd: './services/transaction-statistics',
			pid_file: './pids/service_transaction_statistics.pid',
			out_file: './logs/service_transaction_statistics.log',
			error_file: './logs/service_transaction_statistics.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '300M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_STATISTICS_REDIS: 'redis://localhost:6379/1',
				SERVICE_STATISTICS_MYSQL: 'mysql://lisk:password@localhost:3306/lisk',
				TRANSACTION_STATS_HISTORY_LENGTH_DAYS: '366',
			},
		},
		{
			name: 'lisk-service-market',
			script: 'app.js',
			cwd: './services/market',
			pid_file: './pids/service_market.pid',
			out_file: './logs/service_market.log',
			error_file: './logs/service_market.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '300M',
			autorestart: true,
			env: {
				// --- Remember to set the properties below
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_MARKET_REDIS: 'redis://localhost:6379/2',
				SERVICE_MARKET_FIAT_CURRENCIES: 'EUR,USD,CHF,GBP,RUB',
				SERVICE_MARKET_TARGET_PAIRS: 'LSK_BTC,LSK_EUR,LSK_USD,LSK_CHF,BTC_EUR,BTC_USD,BTC_CHF',
				// EXCHANGERATESAPI_IO_API_KEY: ''
			},
		},
		{
			name: 'lisk-service-export',
			script: 'app.js',
			cwd: './services/export',
			pid_file: './pids/service_export.pid',
			out_file: './logs/service_export.log',
			error_file: './logs/service_export.err',
			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
			watch: false,
			kill_timeout: 10000,
			max_memory_restart: '300M',
			autorestart: true,
			env: {
				SERVICE_BROKER: 'redis://localhost:6379/0',
				SERVICE_EXPORT_REDIS: 'redis://localhost:6379/3',
				SERVICE_EXPORT_REDIS_VOLATILE: 'redis://localhost:6379/4',
			},
		},
	],
};
----
====

== Microservice Configurations
In this section, we discuss the common and specific configurations of all the microservices of Lisk Service.

=== Common Configurations



[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
Must be identical for all micro-services.
Make sure that all micro-services are able to connect with the common Redis.
| redis://localhost:6379/0
 
| `SERVICE_LOG_LEVEL`
| string
| Default log level; Available options are `trace`, `debug`, `info`, `warn`, `error` and `fatal`.
| info
 
| `SERVICE_LOG_STDOUT`
| string
| Enable asynchronous console output such as non-blocking or preferred.
| true

| `SERVICE_LOG_CONSOLE`
| string
| Plain JavaScript console.log() output (blocking),  only for debug
| false

| `SERVICE_LOG_FILE`
| string
| File path to the service log file. ./logs/service.log
| false

| `SERVICE_LOG_GELF`
| string
| Log output in GELF for remote logging. Graylog localhost:12201/udp
| false
|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-gateway',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    ENABLE_HTTP_API: 'http-status,http-version3,http-exports',
                    ENABLE_WS_API: 'blockchain,rpc-v3',
                    JSON_RPC_STRICT_MODE: 'false',
                    // [...]
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====

=== Gateway

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `PORT`
| string
| Port that provides the possibility to connect with Lisk Service.
| 9901
 
| `JSON_RPC_STRICT_MODE`
| string
| Makes JSON-RPC require a valid JSON-RPC 2.0 envelope.
| false
 
| `ENABLE_HTTP_API`
| string
| Enables particular HTTP APIs listed by a comma.
| http-status,http-version3,http-exports

| `ENABLE_WS_API`
| string
| Enables particular JSON-RPC APIs listed by a comma.
| blockchain,rpc-v3

| `SERVICE_GATEWAY_REDIS_VOLATILE`
| string
| 
| redis://localhost:6379/5

| `GATEWAY_DEPENDENCIES`
| string
| Describes the microservices on which the gateway service depends on.
| indexer,connector

| `WS_RATE_LIMIT_ENABLE`
| string
| To enable websocket rate limit, this environment variable is required to be true.
| false

| `WS_RATE_LIMIT_CONNECTIONS`
| integer
| Number of connections per second.
| 5

| `WS_RATE_LIMIT_DURATION`
| integer
| Defines the duration (in seconds) for which the WS rate should be limited.
| 1

| `ENABLE_REQUEST_CACHING`
| string
| To enable RPC response caching, this environment variable is required to be true.
| true

| `HTTP_RATE_LIMIT_ENABLE`
| string
| To enable `HTTP Rate limit`, this environment variable is required to be true.
| false

| `HTTP_RATE_LIMIT_CONNECTIONS`
| integer
| Max number of requests during window. Defaults to 200 requests
| 200

| `HTTP_RATE_LIMIT_WINDOW`
| integer
| To keep a record of requests in the memory (in seconds). Defaults to 10 seconds
| 10

| `HTTP_CACHE_CONTROL_DIRECTIVES`
| string
| The Cache-Control directives can be overridden with this environment variable.
| public, max-age=10

| `ENABLE_HTTP_CACHE_CONTROL`
| string
| To enable response caching, this environment variable is required to be true.
This would include the Cache-Control header within the responses.
| true

|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-gateway',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    ENABLE_HTTP_API: 'http-status,http-version3,http-exports',
                    ENABLE_WS_API: 'blockchain,rpc-v3',
                    JSON_RPC_STRICT_MODE: 'false',
                    // [...]
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====


=== Connector

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `LISK_APP_HTTP`
| string
| URL to connect with the Lisk SDK-based application node over HTTP.
| http://127.0.0.1:7887
 
| `LISK_APP_WS`
| string
| URL to connect with the Lisk SDK-based application node over WebSocket.
| ws://localhost:7887

| `GEOIP_JSON`
| string
| URL of GeoIP server
| https://geoip.lisk.com/json

| `USE_LISK_IPC_CLIENT`
| string
| Boolean flag to enable IPC-based connection to the Lisk SDK-based application node.
| true 

| `GENESIS_BLOCK_URL`
| string
| URL of the Lisk SDK-based application' genesis block. Only to be used when the genesis block is large enough to be transmitted over API calls within the timeout.
| 

| `LISK_APP_DATA_PATH`
| string
| Data path to connect with the Lisk SDK-based application node over IPC.
| ~/.lisk/lisk-core
|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-blockchain-connector',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    LISK_APP_HTTP: 'http://127.0.0.1:7887',
                    LISK_APP_WS: 'ws://localhost:7887',
                    GEOIP_JSON: 'https://geoip.lisk.com/json',
                    USE_LISK_IPC_CLIENT: 'true',
                    GENESIS_BLOCK_URL: '',
                    LISK_APP_DATA_PATH: '~/.lisk/lisk-core',
                    // [...]
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====



=== Coordinator

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_MESSAGE_QUEUE_REDIS`
| string
| URL of the job queue to schedule the indexing jobs (Redis).
| redis://localhost:6379/3

|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-blockchain-coordinator',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    SERVICE_MESSAGE_QUEUE_REDIS: 'redis://localhost:6379/3',
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====


=== Indexer

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_INDEXER_MYSQL`
| string
| Connection string of the MySQL instance that the microservice connects to.
| mysql://lisk:password@localhost:3306/lisk

| `SERVICE_MESSAGE_QUEUE_REDIS`
| string
| URL of the job queue to process the scheduled indexing jobs by the Blockchain Coordinator (Redis).
| redis://localhost:6379/3

| `SERVICE_INDEXER_REDIS_VOLATILE`
| string
| URL of the volatile cache storage (Redis).
| redis://localhost:6379/2

| `ENABLE_DATA_RETRIEVAL_MODE`
| string
| Boolean flag to enable the Data Service mode.
| true

| `ENABLE_INDEXING_MODE`
| string
| Boolean flag to enable the Data Indexing mode.
| true

| `ENABLE_PERSIST_EVENTS`
| string
| Boolean flag to permanently maintain the events in the MySQL database.
| false

|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
			    name: 'lisk-service-blockchain-indexer',
                // [...]
                env: {
					// --- Remember to set the properties below
					SERVICE_BROKER: 'redis://localhost:6379/0',
					SERVICE_INDEXER_CACHE_REDIS: 'redis://localhost:6379/1',
					SERVICE_INDEXER_REDIS_VOLATILE: 'redis://localhost:6379/2',
					SERVICE_MESSAGE_QUEUE_REDIS: 'redis://localhost:6379/3',
					SERVICE_INDEXER_MYSQL: 'mysql://lisk:password@localhost:3306/lisk',
					ENABLE_DATA_RETRIEVAL_MODE: 'true',
					ENABLE_INDEXING_MODE: 'true',
					ENABLE_PERSIST_EVENTS: 'false',
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====



=== Blockchain application registry
[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_APP_REGISTRY_MYSQL`
| string
| Connection string of the MySQL instance that the microservice connects to.
| mysql://lisk:password@localhost:3306/lisk

| `ENABLE_REBUILD_INDEX_AT_INIT`
| string
| Boolean flag to truncate the index and rebuild at application init.
| false

|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-blockchain-app-registry',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    SERVICE_APP_REGISTRY_MYSQL: 'mysql://lisk:password@localhost:3306/lisk',
                    ENABLE_REBUILD_INDEX_AT_INIT: 'false',
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====


=== Fee estimator

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_FEE_ESTIMATOR_CACHE`
| string
| URL of the cache storage (Redis).
| redis://localhost:6379/1

| `ENABLE_FEE_ESTIMATOR_QUICK`
| string
| Enable quick algorithm for fee estimation
| true

| `ENABLE_FEE_ESTIMATOR_FULL`
| string
| Enable full algorithm for fee estimation
| false
|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-fee-estimator',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    SERVICE_FEE_ESTIMATOR_CACHE: 'redis://localhost:6379/1',
					ENABLE_FEE_ESTIMATOR_QUICK: 'true',
					ENABLE_FEE_ESTIMATOR_FULL: 'false',
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====



=== Transaction statistics

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_STATISTICS_MYSQL`
| string
| Connection string of the MySQL instance that the microservice connects to.
| mysql://lisk:password@localhost:3306/lisk

| `SERVICE_STATISTICS_REDIS`
| string
| URL of the cache storage (Redis).
| redis://localhost:6379/1

| `TRANSACTION_STATS_HISTORY_LENGTH_DAYS`
| string
| The number of days for which the transaction statistics need to be built in retrospect to the application init.
| 366

|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-transaction-statistics',
                // [...]
                env: {
                    // --- Remember to set the properties below
					SERVICE_BROKER: 'redis://localhost:6379/0',
					SERVICE_STATISTICS_REDIS: 'redis://localhost:6379/1',
					SERVICE_STATISTICS_MYSQL: 'mysql://lisk:password@localhost:3306/lisk',
					TRANSACTION_STATS_HISTORY_LENGTH_DAYS: '366',
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====

=== Market

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_MARKET_REDIS`
| string
| URL of the cache storage (Redis).
| redis://localhost:6379/2

| `EXCHANGERATESAPI_IO_API_KEY`
| string
| Access key to fetch data from the "exchangeratesapi.io" API.
| 

| `SERVICE_MARKET_FIAT_CURRENCIES`
| string
| Fiat currencies used for price calculation. 
All FIAT currencies used here need to be comma separated
| EUR,USD,CHF,GBP,RUB 

| `SERVICE_MARKET_TARGET_PAIRS`
| string
| Exchange rates exposed to the Gateway. Must be comma separated
| LSK_BTC,LSK_EUR,BTC_CHF


| `EXCHANGERATESAPI_IO_API_KEY`
| string
| Optional API key for https://exchangeratesapi.io/
`/market/prices` endpoint will respond with additional data, specifically the exchange rates for various cryptocurrencies in other fiat currencies.
The free plan would suffice for the purpose of Lisk Service.
|  


|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-market',
                // [...]
                env: {
                    // --- Remember to set the properties below
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    SERVICE_MARKET_REDIS: 'redis://localhost:6379/2',
                    TRANSACTION_STATS_HISTORY_LENGTH_DAYS: '100',
					SERVICE_MARKET_FIAT_CURRENCIES: 'EUR,USD,CHF,GBP,RUB',
					SERVICE_MARKET_TARGET_PAIRS: 'LSK_BTC,LSK_EUR,LSK_USD,LSK_CHF,BTC_EUR,BTC_USD,BTC_CHF',
					// EXCHANGERATESAPI_IO_API_KEY: ''
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====

=== Export

[tabs]
=====
Properties::
+
--
[cols="2,1,3,3",options="header",stripes="hover"]
|===
|Property's Name
|Datatype
|Description
|Sample

| `SERVICE_BROKER`
| string
| URL of the microservice message broker (NATS or Redis).
| redis://localhost:6379/0
 
| `SERVICE_EXPORT_REDIS`
| string
| URL of the permanent cache storage (Redis).
| redis://localhost:6379/3

| `SERVICE_EXPORT_REDIS_VOLATILE`
| string
| URL of the volatile cache storage (Redis).
| redis://localhost:6379/4

|===

--
Sample::
+
--
[source,js]
----
module.exports = {
	apps: [
		{
            // Other types of configurations.
            {
                name: 'lisk-service-export',
                // [...]
                env: {
                    SERVICE_BROKER: 'redis://localhost:6379/0',
                    SERVICE_EXPORT_REDIS: 'redis://localhost:6379/3',
                    SERVICE_EXPORT_REDIS_VOLATILE: 'redis://localhost:6379/4',
                },
		    },
            // Other types of configurations.
        }
	],
};
----
--
=====


=== MySQL Snapshot settings

Configurations to sync Lisk Service from an existing snapshot, to speed up the sync process.

[source,bash]
----
# Enable or disable apply snapshot feature
ENABLE_APPLY_SNAPSHOT=true

# Custom snapshot url (Expected to end with sql.gz)
INDEX_SNAPSHOT_URL='https://snapshots.lisk.io/mainnet/service.sql.gz'

# When the MySQL is hosted as a docker-compose service, set the following environment variables:
# Set docker-compose file path (use absolute path)
DOCKER_COMPOSE_FILEPATH='/Users/lisk/lisk-service/jenkins/mysql/docker-compose.yml'

# Set MySQL service name as defined in the above docker-compose file
DOCKER_MYSQL_SERVICE_NAME=mysql
----


=== External services

[source,bash]
----
# Lisk static assets, i.e. known account lists
LISK_STATIC=https://static-data.lisk.com

# Lisk Service geolocation backend
GEOIP_JSON=https://geoip.lisk.com/json
----

=== Deprecated settings

[source,bash]
----
# This setting is required only for SDK version 4 or lower.
LISK_CORE_HTTP=https://mainnet.lisk.com # Lisk Core HTTP URL
----



// == Common settings

// These options are available for all micro-services provided by Lisk Service.

// === Service broker

// [source,bash]
// ----
// # Must be identical for all micro-serivces
// # Make sure that all micro-services are able to connect with the common Redis
// SERVICE_BROKER=redis://localhost:6379/0
// ----

// === Logging configuration

// [source,bash]
// ----
// SERVICE_LOG_LEVEL=info    # Default log level. TRACE < DEBUG < INFO < WARN < ERROR < FATAL
// SERVICE_LOG_STDOUT=true   # Asynchronous console output (non-blocking, preferred)
// SERVICE_LOG_CONSOLE=false # Plain JavaScript console.log() output (blocking),  only for debug
// SERVICE_LOG_FILE=false    # file path ex. ./logs/service.log
// SERVICE_LOG_GELF=false    # GELF output for remote logging ex. Graylog localhost:12201/udp
// ----

// == Gateway settings

// === Server settings

// [source,bash]
// ----
// # Port that provides the possibility to connect with Lisk Service
// # For HTTP and WebSocket
// PORT=9901
// HOST=0.0.0.0   # or 127.0.0.1 for localhost
// ----

// === API settings

// [source,bash]
// ----
// # Enable certain APIs (HTTP & WebSocket)
// # Use comma separated list
// ENABLE_HTTP_API=http-status,http-version2
// ENABLE_WS_API=blockchain,rpc-v2
// ----

// [NOTE]

// Since the SDK version 5, the HTTP APIs `http-version1`,`http-version1-compat` and WebSocket APIs `rpc`,`rpc-v1` are considered deprecated.
// Please use only version2 APIs when connecting to the SDKv5-based node.

// === Caching

// [source,bash]
// ----
// # To enable response caching, the ENABLE_HTTP_CACHE_CONTROL environment
// # variable is required to be true. This would include the Cache-Control
// # header within the responses.
// ENABLE_HTTP_CACHE_CONTROL=true

// # The `Cache-Control` directives can be overridden with the `HTTP_CACHE_CONTROL_DIRECTIVES`
// # environment variable and currently defaults to `public, max-age=10`.
// HTTP_CACHE_CONTROL_DIRECTIVES='public, max-age=10'

// # To enable RPC response caching, the `ENABLE_REQUEST_CACHING` environment
// # variable is required to be true.
// ENABLE_REQUEST_CACHING=true
// ----

// === Websocket settings

// [source,bash]
// ----
// # To enable websocket rate limit, the `WS_RATE_LIMIT_ENABLE` environment variable is required to be true.
// # Number of connections per second can be set using the
// # `WS_RATE_LIMIT_CONNECTIONS` and `WS_RATE_LIMIT_DURATION` environment
// # variable. It currently defaults to `5 connections per second`
// WS_RATE_LIMIT_ENABLE=true
// WS_RATE_LIMIT_CONNECTIONS=5
// WS_RATE_LIMIT_DURATION=1
// ----

// === Compatibility settings

// [source,bash]
// ----
// # To enable `HTTP Rate limit`, the `HTTP_RATE_LIMIT_ENABLE` environment variable is required to be true.
// # The `HTTP Rate limit` directives can be set using the `HTTP_RATE_LIMIT_WINDOW` and the `HTTP_RATE_LIMIT_CONNECTIONS` environment
// # variable.
// HTTP_RATE_LIMIT_ENABLE=true
// HTTP_RATE_LIMIT_WINDOW=10 # To keep a record of requests in the memory (in seconds). Defaults to 10 seconds
// HTTP_RATE_LIMIT_CONNECTIONS=200 # Max number of requests during window. Defaults to 200 requests
// ----

// === Compatibility settings

// [source,bash]
// ----
// # Enabled requires clients to pass the full JSON-RPC envelope.
// # Disabled allows clients to pass only `method` in the request
// # and does not check the envelope whether it has `jsonrpc: "2.0"` or not.
// JSON_RPC_STRICT_MODE=false
// ----

// == Lisk settings

// === Node settings

// [source,bash]
// ----
// LISK_CORE_WS=ws://localhost:8080       # Lisk Core WebSocket RPC API
// # Use host.docker.internal instead of localhost, if Lisk Service runs in Docker
// # LISK_CORE_WS=ws://host.docker.internal:8080
// LISK_CORE_CLIENT_TIMEOUT=30            # Lisk Core client timeout (in seconds)
// ----



// === Internal cache & persistence

// [source,bash]
// ----
// # Local Redis cache with persistency for Core microservice
// # Refer to the /docker/redis/redis.persistent.conf for more details
// # Note: SERVICE_BROKER uses a different DB
// SERVICE_CORE_REDIS=redis://localhost:6379/1

// # Local Redis LRU cache for Core microservice
// # This should be a separate instance in the production
// # Refer to the /docker/redis/redis.volatile.conf for more details
// SERVICE_CORE_REDIS_VOLATILE=redis://localhost:6379/2

// # MySQL settings
// SERVICE_CORE_MYSQL=mysql://lisk:password@localhost:3306/lisk_service_core

// # MySQL install (for local Docker container)
// MYSQL_ROOT_PASSWORD=password
// MYSQL_DATABASE=lisk
// MYSQL_USER=lisk
// MYSQL_PASSWORD=password
// ----



// === Indexing

// [source,bash]
// ----
// # Important: The number of blocks makes the process responsible of creating
// # and maintaining search index of the given number of blocks behind the current height.
// #
// # indexNumOfBlocks = 0 means that index will consist of all blocks.
// #
// # The block index may trigger indexing of other entities that are part of the block
// # such as transactions, accounts, votes etc.
// INDEX_N_BLOCKS=202
// ----

// === Transaction statistics

// [source,bash]
// ----
// # Enable or disable transaction statistics feature
// ENABLE_TRANSACTION_STATS=true

// # Set update interval to 1 hour
// TRANSACTION_STATS_UPDATE_INTERVAL=3600 # seconds

// # How many days would be analyzed
// TRANSACTION_STATS_HISTORY_LENGTH_DAYS=5
// ----

// === Fee estimator

// [source,bash]
// ----
// # Enable quick algorithm
// ENABLE_FEE_ESTIMATOR_QUICK=true

// # Enable full algorithm
// ENABLE_FEE_ESTIMATOR_FULL=false

// # How many blocks are analyzed during coldstart
// FEE_EST_COLD_START_BATCH_SIZE=1

// # At what height does the blockchain start using dynamic fees
// FEE_EST_DEFAULT_START_BLOCK_HEIGHT=1

// # Estimated moving average algorithm configuration
// # Extra settings for advanced users. They might be useful for getting
// # more precise results under specific circumstances.
// # The default settings are sufficient for most environments.
// FEE_EST_EMA_BATCH_SIZE=20
// FEE_EST_EMA_DECAY_RATE=0.5
// FEE_EST_WAVG_DECAY_PERCENTAGE=10
// ----


// == Market settings

// [source,bash]
// ----
// # FIAT currencies used for price calculation
// # All FIAT currencies used in SERVICE_MARKET_TARGET_PAIRS need to be listed by comma
// # and the EXCHANGERATESAPI_IO_API_KEY needs to be provided.
// SERVICE_MARKET_FIAT_CURRENCIES=EUR,USD,CHF,GBP,RUB

// # Exchange rates exposed to the Gateway, listed by a comma
// SERVICE_MARKET_TARGET_PAIRS=LSK_BTC,LSK_EUR,BTC_CHF

// # Optional API key for https://exchangeratesapi.io/
// # /market/prices endpoint will respond with additional data, specifically the exchange rates for various cryptocurrencies in other fiat currencies.
// # The free plan would suffice for the purpose of Lisk Service.
// EXCHANGERATESAPI_IO_API_KEY=EXCHANGERATESAPI_IO_API_KEY

// # Local Redis cache for the Market microservice
// # Required, if Lisk Service is not running in Docker
// SERVICE_MARKET_REDIS=redis://localhost:6379/2
// ----

