= Configuration with PM2
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to configure Lisk Service with PM2.
:toc:
:imagesdir: ../assets/images
:page-previous: /lisk-service/setup/source.html
:page-previous-title: Installation from source code
:page-next: /lisk-service/management/source.html
:page-next-title: PM2 commands

:url_pm2: https://pm2.keymetrics.io/

:url_management_pm2: management/source.adoc
:url_references_config: configuration/index.adoc
:url_default_config: configuration/index.adoc#default-configurations

== Custom configuration
Lisk Service offers a set of xref:{url_default_config}[Default Configurations], which can be customized as per the requirement.
To create a custom configuration, it is recommended to copy the default configuration file and use the copy of the said file for customization.

.Working directory: ./lisk-service/
[source,bash]
----
cp ecosystem.config.js ecosystem.custom.config.js
----

Now it is possible to open the new file `ecosystem.custom.config.js` and adjust it as desired.

Lisk Service can be configured in various ways by setting environment variables.

TIP: All available configuration options are described in the xref:{url_references_config}[Configuration reference].

Once customized, you can start Lisk Service with the custom ecosystem file by executing the following command:

.Working directory: ./lisk-service/
[source,bash]
----
pm2 start ecosystem.custom.config.js
----

Finally, if you want to use `yarn start` and `yarn stop` to start and stop Lisk Service with the custom configuration, don't forget to update the `scripts` in `package.json`:

.Working directory: ./lisk-service/
[source,json]
----
{
  //[...]
  "scripts": {
    "start": "pm2 start ecosystem.custom.config.js",
    "stop": "pm2 delete ecosystem.custom.config.js",
  //[...]
  }
}
----

Additional commands for managing Lisk Service with PM2 are described on the xref:{url_management_pm2}[PM2 commands] page.
