= Docker commands
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to manage Lisk Service with Docker.
:toc:
:idseparator: -
:idprefix:
:experimental:
:imagesdir: ../assets/images

:url_config: configuration/docker.adoc


== Start

.Inside of the `lisk-service` root folder
[source,bash]
----
make up
----

This will start Lisk Service with the default configuration, which in turn will connect to a Lisk Core Mainnet node.

In case a different node or network shall be used, xref:{url_config}[configure] Lisk Service accordingly.

== Stop

.Inside of the `lisk-service` root folder
[source,bash]
----
make down
----

This will stop Lisk Service.

== Show status of Docker containers

[source,bash]
----
docker ps
----

== Reset Lisk Service database

To reset the database of Lisk Service, drop the respective MySQL and Redis databases.

Before resetting the database, stop Lisk Service:

 make down

Now connect to the Docker container in which you wish to reset the database. If you are not sure what to choose here, check the available containers via <<show-status-of-docker-containers>>.

[source,bash]
----
$ docker exec -it lisk-service_mysql_core_1 bash # <1>
----

<1> Connect to the interactive shell of the MySQL Docker container in which you wish to reset the MySQL database.

=== Drop Database

[tabs]
====
MySQL DB::
+
--
[source,bash]
----
root@f1413b535254:/# mysql -ulisk -ppassword # <1>
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2044
Server version: 8.0.27 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> drop database lisk; # <2>
mysql> create database lisk; # <3>
mysql> quit; # <4>
----
<1> Login to MySQL with the `lisk` user.
<2> Drop the `lisk` database.
<3> Create a fresh database `lisk`.
<4> Log out from MySQL by typing `quit;`.
Log out of the docker container by pressing kbd:[CRTL] + kbd:[D].

--
MariaDB::
+
--
MariaDB also uses the same SQL commands for querying and manipulating the relevant data, including data storage, client libraries and replication.


[source,bash]
----
root@f1413b535254:~# docker exec -it lisk_mariadb mysql -uroot -p # <1>
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 9
Server version: 10.7.8-MariaDB-1:10.7.8+maria~ubu2004 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> drop database lisk; # <2>
Query OK, 0 rows affected (0.009 sec)

MariaDB [(none)]> create database lisk; # <3>
Query OK, 1 row affected (0.001 sec)

MariaDB [(none)]> exit; # <4>
Bye
----
<1> Login to MariaDB with the `lisk` user.
<2> Drop the `lisk` database.
<3> Create a fresh database `lisk`.
<4> Log out by typing `quit;`.
Log out of the docker container by pressing kbd:[CRTL] + kbd:[D].
--
====

=== Flush Redis DB

Reset the databases for Redis after dropping the MySQL database:

[source,bash]
----
sudo docker exec -it lisk-service_redis_core_persistent_1 /bin/sh
redis-cli flushall
----

TIP: Log out of the docker container again by pressing kbd:[CRTL] + kbd:[D].

[NOTE]
====
The `flushall` command removes all existing Redis databases:

> Deletes all the keys of all the existing databases, not just the current selected one. This command never fails.

For more information check the Redis documentation: https://redis.io/commands/FLUSHALL[FLUSHALL]

To flush only a particular DB in Redis, execute the following command instead:
----
 redis-cli -n <db_number> flushdb
----
====

=== Start Lisk Service

After the databases are reset, start Lisk Service again as usual:

 make up

NOTE: When Lisk Service is started again after a database reset, then the process to reindex all the data is initiated.
This can be quite time-consuming when the chain is long, spanning over hours.

== Logging

To check the logs for the different microservices of Lisk Service, use the command `docker container logs CONTAINER`, where `CONTAINER` is the respective Docker container that holds the logs you wish to view.

For example, to see the logs for the Gateway microservice, execute the following command:

[source,bash]
----
docker container logs lisk-service_gateway_1
----
