@Library('lisk-jenkins') _

def echoBanner(msg) {
	echo '----------------------------------------------------------------------'
	echo msg
	echo '----------------------------------------------------------------------'
}

pipeline {
	agent { node { label 'lisk-service' } }
	options {
		timeout(time: 10, unit: 'MINUTES')
	}
	stages {
		stage ('Build deps') {
			steps {
				script { echoBanner(STAGE_NAME) }
				nvm(getNodejsVersion()) {
					dir('./') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./framework') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./services/core') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./services/market') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./services/newsfeed') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./services/export') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./services/gateway') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./services/template') { sh 'npm i --registry https://npm.lisk.com' }
					dir('./tests') { sh 'npm i --registry https://npm.lisk.com' }
				}
			}
		}
		stage ('Check linting') {
			steps {
				script { echoBanner(STAGE_NAME) }
				nvm(getNodejsVersion()) {
					sh 'npm run eslint'
				}
			}
		}
		stage('Perform unit tests') {
			steps {
				script { echoBanner(STAGE_NAME) }
				nvm(getNodejsVersion()) {
					dir('./framework') { sh "npm run test:unit" }
					dir('./services/core') { sh "npm run test:unit" }
					dir('./services/market') { sh "npm run test:unit" }
					dir('./services/newsfeed') { sh "npm run test:unit" }
					dir('./services/export') { sh "npm run test:unit" }
				}
			}
		}
	}
	post {
		failure {
			script { echoBanner('Failed to run the pipeline') }
		}
		cleanup {
			script {
			    echoBanner('Cleaning up...')
				nvm(readFile('.nvmrc').trim()) {
					echoBanner('Removing dependencies')
					sh 'make clean-local'
				}
			}
			echo 'All installed dependencies successfully removed'
		}
	}
}
// vim: filetype=groovy
