/*
 * LiskHQ/lisk-service
 * Copyright © 2021 Lisk Foundation
 *
 * See the LICENSE file at the top-level directory of this distribution
 * for licensing information.
 *
 * Unless otherwise agreed in a custom licensing agreement with the Lisk Foundation,
 * no part of this software, including this file, may be copied, modified,
 * propagated, or distributed except according to the terms contained in the
 * LICENSE file.
 *
 * Removal or modification of this copyright notice is prohibited.
 *
 */
const news = [
	{
		content_orig: 'Every month the Lisk Foundation provides a financial report in which monthly expenditures are transparently broken down into different categories. In the first part of the report, you can check up on all fiat currency and cryptocurrency assets currently in possession of the Foundation. In the expenditures section of the Financial Update, you can see how much the Foundation has spent on various aspects of the Lisk&#039;s growth.',
		content_t: 'Every month the Lisk Foundation provides a financial report in which monthly expenditures are transparently broken down into different categories. In the first part of the report, you can check up on all fiat currency and cryptocurrency assets currently in possession of the Foundation. In the expenditures section of the Financial Update, you can see how much the Foundation has spent on various aspects of the Lisk&#039;s growth.',
		source: 'drupal_lisk_general',
		title: 'Financial Update for January 2021',
		source_id: '8d2067e723f7d4229bf33502b1b0c2906c68a853',
		created_at: 1612965420,
		modified_at: 1612965420,
		url: 'https://lisk.com/blog/foundation/financial-update-january-2021',
		author: 'Lisk',
		image_url: 'https://lisk.com/sites/default/files/styles/blog_main_image_xl_retina/public/images/2021-02/financial-update-january-2021-Blog%402x.png?itok=W-6nunXO',
	},
	{
		content_orig: 'RT @CryptoJobsList: 👍 Featured opportunity: 💼 Backend Developer -\nBlockchain/Node.js at 🏛️ Lightcurve @LiskHQ 📍 Berlin, Germ Apply now,…',
		content_t: 'RT @CryptoJobsList: 👍 Featured opportunity: 💼 Backend Developer -\nBlockchain/Node.js at 🏛️ Lightcurve @LiskHQ 📍 Berlin, Germ Apply now,…',
		source: 'twitter_lisk',
		title: '',
		source_id: '82f381efdf90f422129cccc52091b461dc4c3200',
		created_at: 1623924505,
		modified_at: 1612965420,
		url: 'https://t.co/gDbz03FbKD',
		author: 'LiskHQ',
		image_url: null,
	},
];

const drupalData = [
	{
		title: 'Introducing the Lisk Community Squad',
		category: 'Announcement',
		created: '06/22/2021 - 09:52',
		link: '/blog/announcement/introducing-lisk-community-squad',
		author: 'Lisk',
		description: 'As a consequence of Lisk’s growth, development, and expansion we felt the need to encourage and include core community members even further by giving them a chance to make a difference in our community and ecosystem. We called them the Lisk Community Squad, and they are the voice of our community. This blog post provides further information as to what led to the creation of the squad, the actual roles, and responsibilities of the current team members as well as an insight on how to join.',
		image: '/sites/default/files/styles/blog_main_image_xl_retina/public/images/2021-06/introducing-the-community-squad-SOCIAL%402x%20%281%29.png?itok=rARrqicl',
		nid: '1090',
		content: '\n      \n\n\n  \n\n      As a consequence of Lisk’s growth, development, and expansion we felt the need to encourage and include core community members even further by giving them a chance to make a difference in our community and ecosystem. We called them the Lisk Community Squad, and they are the voice of our community. This blog post provides further information as to what led to the creation of the squad, the actual roles, and responsibilities of the current team members as well as an insight on how to join.\n\n \n\nThe Squad\n\nAt the moment, the Lisk Community Squad is composed of 11 individuals…, \n  \n  \n  \n\n\n\n\n      \n                \n\n\n            \n\n  \n\n      \n\n\n    \n      \n    \n    \n, \n      \n\n\n  \n\n      Join the Lisk Community Squad\n\nAs aforementioned, being part of the Lisk Community Squad allows for each member to actively participate and see their efforts coming into fruition with the goal in mind to make the Lisk community a welcoming and engaging environment for existing community members and newcomers.\n\n \n\nThe Lisk Community Squad is the face and voice of our community, which we value immensely, therefore, the group is often included in internal discussions and brainstorming sessions. In addition to this, the group has an exclusive communication channel on our…, \n  \n  \n  \n\n\n\n\n      \n                \n\n\n            \n\n  \n\n      \n\n\n    \n      \n    \n        \n              Our Lisk Mascot cannot contain his excitement for the Lisk Center Berlin to open again and to welcome you all here. \n\n                  \n\n  \n          Zoom in\n      \n\n          \n  \n',
	},
	{
		title: 'Achievements of May 2021',
		category: 'Announcement',
		created: '06/03/2021 - 14:04',
		link: '/blog/announcement/achievements-may-2021',
		author: 'Lisk',
		description: 'At Lisk, we are incredibly proud of our achievements, so at the end of each month, we summarize our latest news, updates, and progress in a single blog post to keep everyone informed and up to date. Help us spread the word by retweeting all our highlights to enable more people to discover what we are working on.',
		image: '/sites/default/files/styles/blog_main_image_xl_retina/public/images/2021-06/achievements-of-may-2021-Main%402x.png?itok=2Zqbp4ob',
		nid: '1081',
		content: '\n      \n\n\n  \n\n      At Lisk, we are incredibly proud of our achievements, so at the end of each month, we summarize our latest news, updates, and progress in a single blog post to keep everyone informed and up to date. Help us spread the word by retweeting all our highlights to enable more people to discover what we are working on.\n\n \n\nLisk SDK Releases\n\nLisk SDK 5.0.5 \n\nIn May we released the Lisk SDK 5.0.5. This release fixes a number of bugs in peer-to-peer, Cryptography, and Framework. More details about this release can be found on GitHub.\n\nHelp us spread the word!\n\n \n\nLisk SDK 5.1.0 …',
	},
];

const normalizedTwitterData = [
	{
		hash: 'fbbee0c6aa82444958d311309569d916dd095748',
		author: 'LiskHQ',
		content_orig: '🏔️ Another exciting month for @LiskHQ. Here is our latest achievements blog post.',
		content_t: '🏔️ Another exciting month for @LiskHQ. Here is our latest achievements blog post.',
		image_url: undefined,
		source: 'twitter_lisk',
		source_id: '1410182648325046300',
		created_at: 1619881551,
		modified_at: 1619881551,
		title: undefined,
		url: 'https://twitter.com/i/web/status/1410182648325046278',
	},
	{
		hash: 'cf1aad50574079f0fd591192a575f76ea726e775',
		author: 'LiskHQ',
		content_orig: 'RT @ManuGowda_Ns: Solve real world problems in 3 simple steps using #lisksdk @LiskHQ.\n'
			+ '\n'
			+ '1. Bootstrap blockchain application\n'
			+ '2. Add your bloc…',
		content_t: 'RT @ManuGowda_Ns: Solve real world problems in 3 simple steps using #lisksdk @LiskHQ.\n'
			+ '\n'
			+ '1. Bootstrap blockchain application\n'
			+ '2. Add your bloc…',
		image_url: undefined,
		source: 'twitter_lisk',
		source_id: '1410177519282798600',
		created_at: 1619047495,
		modified_at: 1619047495,
		title: undefined,
		url: 'https://t.co/oyheDOWV8v',
	},
	{
		hash: '2e868417c5347d26d8f77e502b48480ae9d63745',
		author: 'LiskHQ',
		content_orig: 'Attention #developers. 🧑‍💻\n'
			+ '\n'
			+ 'Want to build your own blockchain application using #JavaScript? Use the @LiskHQ #SDK.… https://t.co/8JtbRkSgO5',
		content_t: 'Attention #developers. 🧑‍💻\n'
			+ '\n'
			+ 'Want to build your own blockchain application using #JavaScript? Use the @LiskHQ #SDK.… https://t.co/8JtbRkSgO5',
		image_url: undefined,
		source: 'twitter_lisk',
		source_id: '1410171102182219800',
		created_at: 1619045965,
		modified_at: 1619045965,
		title: undefined,
		url: 'https://t.co/8JtbRkSgO5',
	},
];

const tweetObject = {
	created_at: 'Mon Sep 06 18:20:24 +0000 2021',
	id: 1434944587202711600,
	id_str: '1434944587202711558',
	text: 'Lisk Core v3.0.1 was released today. 🚀\n\n🔧 This release fixes several bugs identified in the v3.0.0 lisk-core CLI co… https://t.co/nRHwyO5DWw',
	truncated: true,
	entities: {
		hashtags: [],
		symbols: [],
		user_mentions: [],
		urls: [
			{
				url: 'https://t.co/nRHwyO5DWw',
				expanded_url: 'https://twitter.com/i/web/status/1434944587202711558',
				display_url: 'twitter.com/i/web/status/1…',
				indices: [117, 140],
			},
		],
	},
	source: '<a href ="https://twitter.com" rel="nofollow">Twitter for Advertisers</a>',
	in_reply_to_status_id: null,
	in_reply_to_status_id_str: null,
	in_reply_to_user_id: null,
	in_reply_to_user_id_str: null,
	in_reply_to_screen_name: null,
	user: {
		id: 4736263474,
		id_str: '4736263474',
		name: 'Lisk',
		screen_name: 'LiskHQ',
		location: 'Zug, Switzerland',
		description: 'Lisk is an open source blockchain application platform.We empower developers with a software development kit for blockchain applications written in JavaScript.',
		url: 'https://t.co/V8cEdO1sxX',
		entities: {
			url: {
				urls: [
					{
						url: 'https://t.co/V8cEdO1sxX',
						expanded_url: 'https://lisk.com/',
						display_url: 'lisk.com',
						indices: [0, 23],
					},
				],
			},
			description: {
				urls: [],
			},
		},
		protected: false,
		followers_count: 197701,
		friends_count: 595,
		listed_count: 2314,
		created_at: 'Thu Jan 07 16: 42: 08 + 0000 2016',
		favourites_count: 8488,
		utc_offset: null,
		time_zone: null,
		geo_enabled: false,
		verified: true,
		statuses_count: 4034,
		lang: null,
		contributors_enabled: false,
		is_translator: false,
		is_translation_enabled: false,
		profile_background_color: '000000',
		profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_tile: false,
		profile_image_url: 'http://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_image_url_https: 'https://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_banner_url: 'https://pbs.twimg.com/profile_banners/4736263474/1574261605',
		profile_link_color: '1B95E0',
		profile_sidebar_border_color: '000000',
		profile_sidebar_fill_color: '000000',
		profile_text_color: '000000',
		profile_use_background_image: false,
		has_extended_profile: false,
		default_profile: false,
		default_profile_image: false,
		following: false,
		follow_request_sent: false,
		notifications: false,
		translator_type: 'none',
		withheld_in_countries: [],
	},
	geo: null,
	coordinates: null,
	place: null,
	contributors: null,
	is_quote_status: false,
	retweet_count: 25,
	favorite_count: 113,
	favorited: false,
	retweeted: false,
	lang: 'en',
};

const retweetObject = {
	created_at: 'Thu Sep 02 14:59:30 +0000 2021',
	id: 1433444480162599000,
	id_str: '1433444480162598919',
	text: "RT @QICcommunity: Let's go back in summer for just a moment and recap top #crypto projects with the most active developers☀️\n\n$LSK 1,277 co…",
	truncated: false,
	entities: {
		hashtags: [
			{
				text: 'crypto',
				indices: [74, 81],
			},
		],
		symbols: [
			{
				text: 'LSK',
				indices: [126, 130],
			},
		],
		user_mentions: [
			{
				screen_name: 'QICcommunity',
				name: 'Quora Inner Circle',
				id: 892425894073118700,
				id_str: '892425894073118720',
				indices: [3, 16],
			},
		],
		urls: [],
	},
	source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
	in_reply_to_status_id: null,
	in_reply_to_status_id_str: null,
	in_reply_to_user_id: null,
	in_reply_to_user_id_str: null,
	in_reply_to_screen_name: null,
	user: {
		id: 4736263474,
		id_str: '4736263474',
		name: 'Lisk',
		screen_name: 'LiskHQ',
		location: 'Zug, Switzerland',
		description: 'Lisk is an open source blockchain application platform. We empower developers with a software development kit for blockchain applications written in JavaScript.',
		url: 'https://t.co/V8cEdO1sxX',
		entities: {
			url: {
				urls: [
					{
						url: 'https://t.co/V8cEdO1sxX',
						expanded_url: 'https://lisk.com/',
						display_url: 'lisk.com',
						indices: [0, 23],
					},
				],
			},
			description: {
				urls: [],
			},
		},
		protected: false,
		followers_count: 197712,
		friends_count: 595,
		listed_count: 2314,
		created_at: 'Thu Jan 07 16:42:08 +0000 2016',
		favourites_count: 8488,
		utc_offset: null,
		time_zone: null,
		geo_enabled: false,
		verified: true,
		statuses_count: 4034,
		lang: null,
		contributors_enabled: false,
		is_translator: false,
		is_translation_enabled: false,
		profile_background_color: '000000',
		profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_tile: false,
		profile_image_url: 'http://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_image_url_https: 'https://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_banner_url: 'https://pbs.twimg.com/profile_banners/4736263474/1574261605',
		profile_link_color: '1B95E0',
		profile_sidebar_border_color: '000000',
		profile_sidebar_fill_color: '000000',
		profile_text_color: '000000',
		profile_use_background_image: false,
		has_extended_profile: false,
		default_profile: false,
		default_profile_image: false,
		following: false,
		follow_request_sent: false,
		notifications: false,
		translator_type: 'none',
		withheld_in_countries: [],
	},
	geo: null,
	coordinates: null,
	place: null,
	contributors: null,
	retweeted_status: {
		created_at: 'Thu Sep 02 10:17:40 +0000 2021',
		id: 1433373553584443400,
		id_str: '1433373553584443396',
		text: "Let's go back in summer for just a moment and recap top #crypto projects with the most active developers☀️\n\n$LSK 1,… https://t.co/O08qgJyi9i",
		truncated: true,
		entities: {
			hashtags: [
				{
					text: 'crypto',
					indices: [56, 63],
				},
			],
			symbols: [
				{
					text: 'LSK',
					indices: [108, 112],
				},
			],
			user_mentions: [],
			urls: [
				{
					url: 'https://t.co/O08qgJyi9i',
					expanded_url: 'https://twitter.com/i/web/status/1433373553584443396',
					display_url: 'twitter.com/i/web/status/1…',
					indices: [117, 140],
				},
			],
		},
		source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
		in_reply_to_status_id: null,
		in_reply_to_status_id_str: null,
		in_reply_to_user_id: null,
		in_reply_to_user_id_str: null,
		in_reply_to_screen_name: null,
		user: {
			id: 892425894073118700,
			id_str: '892425894073118720',
			name: 'Quora Inner Circle',
			screen_name: 'QICcommunity',
			location: 'Quora',
			description: '#1 Quora crypto community\n\n$BTC $ETH $BNB $UNI $ENJ $PRE $SNX $AAVE $THETA $VET $KIN $CHZ $LTO $NEXO $GET',
			url: 'https://t.co/UwXTXOVvJd',
			entities: {
				url: {
					urls: [
						{
							url: 'https://t.co/UwXTXOVvJd',
							expanded_url: 'https://t.me/quorainnercircle',
							display_url: 't.me/quorainnercirc…',
							indices: [0, 23],
						},
					],
				},
				description: {
					urls: [],
				},
			},
			protected: false,
			followers_count: 10522,
			friends_count: 696,
			listed_count: 65,
			created_at: 'Tue Aug 01 16:44:48 +0000 2017',
			favourites_count: 2810,
			utc_offset: null,
			time_zone: null,
			geo_enabled: false,
			verified: false,
			statuses_count: 748,
			lang: null,
			contributors_enabled: false,
			is_translator: false,
			is_translation_enabled: false,
			profile_background_color: '000000',
			profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
			profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
			profile_background_tile: false,
			profile_image_url: 'http://pbs.twimg.com/profile_images/1404827611658743814/9nVC1mG9_normal.jpg',
			profile_image_url_https: 'https://pbs.twimg.com/profile_images/1404827611658743814/9nVC1mG9_normal.jpg',
			profile_banner_url: 'https://pbs.twimg.com/profile_banners/892425894073118720/1628165075',
			profile_link_color: 'FF691F',
			profile_sidebar_border_color: '000000',
			profile_sidebar_fill_color: '000000',
			profile_text_color: '000000',
			profile_use_background_image: false,
			has_extended_profile: true,
			default_profile: false,
			default_profile_image: false,
			following: false,
			follow_request_sent: false,
			notifications: false,
			translator_type: 'none',
			withheld_in_countries: [],
		},
		geo: null,
		coordinates: null,
		place: null,
		contributors: null,
		is_quote_status: false,
		retweet_count: 61,
		favorite_count: 184,
		favorited: false,
		retweeted: false,
		possibly_sensitive: false,
		lang: 'en',
	},
	is_quote_status: false,
	retweet_count: 61,
	favorite_count: 0,
	favorited: false,
	retweeted: false,
	lang: 'en',
};

const mediaTweetObject = {
	created_at: 'Wed Aug 25 09:36:47 +0000 2021',
	id: 1430464160236720000,
	id_str: '1430464160236720130',
	text: 'A new era for #Lisk 🚀 💎 . https://t.co/j463TQooJ5',
	truncated: false,
	entities: {
		hashtags: [
			{
				text: 'Lisk',
				indices: [14, 19],
			},
		],
		symbols: [],
		user_mentions: [],
		urls: [],
		media: [
			{
				id: 1428836780661477400,
				id_str: '1428836780661477384',
				indices: [26, 49],
				media_url: 'http://pbs.twimg.com/media/E9ez01QWQAMN_pq.png',
				media_url_https: 'https://pbs.twimg.com/media/E9ez01QWQAMN_pq.png',
				url: 'https://t.co/j463TQooJ5',
				display_url: 'pic.twitter.com/j463TQooJ5',
				expanded_url: 'https://twitter.com/LiskHQ/status/1430464160236720130/video/1',
				type: 'photo',
				sizes: {
					small: {
						w: 680,
						h: 383,
						resize: 'fit',
					},
					medium: {
						w: 1200,
						h: 675,
						resize: 'fit',
					},
					large: {
						w: 2048,
						h: 1152,
						resize: 'fit',
					},
					thumb: {
						w: 150,
						h: 150,
						resize: 'crop',
					},
				},
			},
		],
	},
	extended_entities: {
		media: [
			{
				id: 1428836780661477400,
				id_str: '1428836780661477384',
				indices: [26, 49],
				media_url: 'http://pbs.twimg.com/media/E9ez01QWQAMN_pq.png',
				media_url_https: 'https://pbs.twimg.com/media/E9ez01QWQAMN_pq.png',
				url: 'https://t.co/j463TQooJ5',
				display_url: 'pic.twitter.com/j463TQooJ5',
				expanded_url: 'https://twitter.com/LiskHQ/status/1430464160236720130/video/1',
				type: 'video',
				sizes: {
					small: {
						w: 680,
						h: 383,
						resize: 'fit',
					},
					medium: {
						w: 1200,
						h: 675,
						resize: 'fit',
					},
					large: {
						w: 2048,
						h: 1152,
						resize: 'fit',
					},
					thumb: {
						w: 150,
						h: 150,
						resize: 'crop',
					},
				},
				video_info: {
					aspect_ratio: [16, 9],
					duration_millis: 88672,
					variants: [{
						bitrate: 832000,
						content_type: 'video/mp4',
						url: 'https://video.twimg.com/amplify_video/1428836780661477384/vid/640x360/b6XtVYM3gJj7wwal.mp4?tag=14',
					}, {
						bitrate: 2176000,
						content_type: 'video/mp4',
						url: 'https://video.twimg.com/amplify_video/1428836780661477384/vid/1280x720/LNhBtWZnkppDMqRP.mp4?tag=14',
					}, {
						content_type: 'application/x-mpegURL',
						url: 'https://video.twimg.com/amplify_video/1428836780661477384/pl/7w443Gw7KJP57WcX.m3u8?tag=14',
					}, {
						bitrate: 288000,
						content_type: 'video/mp4',
						url: 'https://video.twimg.com/amplify_video/1428836780661477384/vid/480x270/XRV3TqGniacU4qyB.mp4?tag=14',
					}],
				},
				additional_media_info: {
					title: 'A new era for #Lisk. ',
					description: 'A new era for #Lisk 🚀 💎 .',
					embeddable: true,
					monetizable: false,
				},
			},
		],
	},
	source: '<a href="https://ads.twitter.com" rel="nofollow">Twitter Ads</a>',
	in_reply_to_status_id: null,
	in_reply_to_status_id_str: null,
	in_reply_to_user_id: null,
	in_reply_to_user_id_str: null,
	in_reply_to_screen_name: null,
	user: {
		id: 4736263474,
		id_str: '4736263474',
		name: 'Lisk',
		screen_name: 'LiskHQ',
		location: 'Zug, Switzerland',
		description: 'Lisk is an open source blockchain application platform. We empower developers with a software development kit for blockchain applications written in JavaScript.',
		url: 'https://t.co/V8cEdO1sxX',
		entities: {
			url: {
				urls: [
					{
						url: 'https://t.co/V8cEdO1sxX',
						expanded_url: 'https://lisk.com/',
						display_url: 'lisk.com',
						indices: [0, 23],
					},
				],
			},
			description: {
				urls: [],
			},
		},
		protected: false,
		followers_count: 197711,
		friends_count: 595,
		listed_count: 2314,
		created_at: 'Thu Jan 07 16:42:08 +0000 2016',
		favourites_count: 8488,
		utc_offset: null,
		time_zone: null,
		geo_enabled: false,
		verified: true,
		statuses_count: 4034,
		lang: null,
		contributors_enabled: false,
		is_translator: false,
		is_translation_enabled: false,
		profile_background_color: '000000',
		profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_tile: false,
		profile_image_url: 'http://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_image_url_https: 'https://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_banner_url: 'https://pbs.twimg.com/profile_banners/4736263474/1574261605',
		profile_link_color: '1B95E0',
		profile_sidebar_border_color: '000000',
		profile_sidebar_fill_color: '000000',
		profile_text_color: '000000',
		profile_use_background_image: false,
		has_extended_profile: false,
		default_profile: false,
		default_profile_image: false,
		following: false,
		follow_request_sent: false,
		notifications: false,
		translator_type: 'none',
		withheld_in_countries: [],
	},
	geo: null,
	coordinates: null,
	place: null,
	contributors: null,
	is_quote_status: false,
	retweet_count: 56,
	favorite_count: 219,
	favorited: false,
	retweeted: false,
	possibly_sensitive: false,
	lang: 'en',
};

const otherTweetObject = {
	created_at: 'Wed Sep 01 17:34:27 +0000 2021',
	id: 1433121084132499500,
	id_str: '1433121084132499460',
	text: "🌟  Lisk's Achievements in August 2021 🌟\n\nAugust was an important one for #Lisk. Check out some of our biggest achievements this month. 💎",
	truncated: false,
	entities: {
		hashtags: [
			{
				text: 'Lisk',
				indices: [73, 78],
			},
		],
		symbols: [],
		user_mentions: [],
		urls: [],
	},
	source: '<a href="https://twitter.com" rel="nofollow">Twitter for Advertisers</a>',
	in_reply_to_status_id: null,
	in_reply_to_status_id_str: null,
	in_reply_to_user_id: null,
	in_reply_to_user_id_str: null,
	in_reply_to_screen_name: null,
	user: {
		id: 4736263474,
		id_str: '4736263474',
		name: 'Lisk',
		screen_name: 'LiskHQ',
		location: 'Zug, Switzerland',
		description: 'Lisk is an open source blockchain application platform. We empower developers with a software development kit for blockchain applications written in JavaScript.',
		url: 'https://t.co/V8cEdO1sxX',
		entities: {
			url: {
				urls: [
					{
						url: 'https://t.co/V8cEdO1sxX',
						expanded_url: 'https://lisk.com/',
						display_url: 'lisk.com',
						indices: [0, 23],
					},
				],
			},
			description: {
				urls: [],
			},
		},
		protected: false,
		followers_count: 197710,
		friends_count: 595,
		listed_count: 2314,
		created_at: 'Thu Jan 07 16:42:08 +0000 2016',
		favourites_count: 8488,
		utc_offset: null,
		time_zone: null,
		geo_enabled: false,
		verified: true,
		statuses_count: 4034,
		lang: null,
		contributors_enabled: false,
		is_translator: false,
		is_translation_enabled: false,
		profile_background_color: '000000',
		profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_tile: false,
		profile_image_url: 'http://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_image_url_https: 'https://pbs.twimg.com/profile_images/1189844389113270272/bZihIuER_normal.png',
		profile_banner_url: 'https://pbs.twimg.com/profile_banners/4736263474/1574261605',
		profile_link_color: '1B95E0',
		profile_sidebar_border_color: '000000',
		profile_sidebar_fill_color: '000000',
		profile_text_color: '000000',
		profile_use_background_image: false,
		has_extended_profile: false,
		default_profile: false,
		default_profile_image: false,
		following: false,
		follow_request_sent: false,
		notifications: false,
		translator_type: 'none',
		withheld_in_countries: [],
	},
	geo: null,
	coordinates: null,
	place: null,
	contributors: null,
	is_quote_status: false,
	retweet_count: 19,
	favorite_count: 83,
	favorited: false,
	retweeted: false,
	lang: 'en',
};

module.exports = {
	news,
	drupalData,
	normalizedTwitterData,
	tweetObject,
	retweetObject,
	mediaTweetObject,
	otherTweetObject,
};
