version: "3"
services:

  template:
    image: lisk/service_template

    depends_on:
      - redis_common
    networks:
      - services_network
    restart: always
    env_file:
      - ./lisk_service/env/common.env

  gateway:
    depends_on:
      - template

networks:
  core_network:
