version: "3"
services:

  core:
    image: lisk/service_core
    depends_on:
      - redis_common
      - postgres_core
      - redis_core
    networks:
      - services_network
      - core_network
    restart: always
    env_file:
      - ./lisk_service/env/common.env
      - ./lisk_service/env/core.env

  postgres_core:
    image: postgres:10-alpine
    volumes:
      - postgres_core_vol:/var/lib/postgresql/data
    networks:
      - core_network
    restart: always

  redis_core:
    image: redis:5-alpine
    volumes:
      - ./redis/redis.persistent.conf:/etc/redis/redis.conf:ro
    networks:
      - core_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping

  gateway:
    depends_on:
      - core

volumes:
  postgres_core_vol:

networks:
  core_network:
