version: "3"
services:

  tests:
    image: lisk/service_tests
    networks:
      - services_network
    environment:
      - SERVICE_ENDPOINT=http://gateway:9901
    restart: always
    command: tail -f /dev/null
