version: "3"
services:

  core:
    image: lisk/service_core
    depends_on:
      - redis_common
      - core_postgres
      - core_redis
    networks:
      - services_network
      - core_network
    restart: always
    environment:
      - SERVICE_BROKER=${SERVICE_BROKER}
      - GEOIP_JSON=${GEOIP_JSON}
      - LISK_CORE_HTTP=${LISK_CORE_HTTP}
      - LISK_CORE_WS=${LISK_CORE_WS}
      - SERVICE_CORE_REDIS=${SERVICE_CORE_REDIS}
      - SERVICE_CORE_POSTGRES=${SERVICE_CORE_POSTGRES}
      - SERVICE_LOG_LEVEL=${SERVICE_LOG_LEVEL}
      - SERVICE_LOG_CONSOLE=${SERVICE_LOG_CONSOLE}
      - SERVICE_LOG_FILE=${SERVICE_LOG_FILE}
      - SERVICE_LOG_GELF=${SERVICE_LOG_GELF}
      - SERVICE_LOG_STDOUT=${SERVICE_LOG_STDOUT}

  core_postgres:
    image: postgres:10-alpine
    volumes:
      - core_postgres_vol:/var/lib/postgresql/data
    networks:
      - core_network
    restart: always
    environment:
      - POSTGRES_DB=${ENV_LISK_DB_DATABASE}
      - POSTGRES_PASSWORD=${ENV_LISK_DB_PASSWORD}
      - POSTGRES_USER=${ENV_LISK_DB_USER}

  core_redis:
    image: redis:5-alpine
    volumes:
      - ./lisk_service/redis.persistent.conf:/etc/redis/redis.conf:ro
    networks:
      - core_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping

  gateway:
    depends_on:
      - core

volumes:
  core_postgres_vol:

networks:
  core_network:
