version: "3"
services:

  core:
    image: lisk/service_core
    depends_on:
      - redis_common
      - redis_core
      - mysql_core
    networks:
      - services_network
      - core_network
    restart: always
    env_file:
      - ./lisk_service/env/common.env
      - ./lisk_service/env/core.env

  redis_core:
    image: redis:5-alpine
    volumes:
      - ./redis/redis.persistent.conf:/etc/redis/redis.conf:ro
    networks:
      - core_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping

  mysql_core:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - core_network
    env_file:
      - ./lisk_service/env/core.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  gateway:
    depends_on:
      - core

volumes:
  mysql-data:

networks:
  core_network:
