version: "3"
services:

  gateway:
    image: lisk/service_gateway
    networks:
      - services_network
    restart: always
    env_file:
      - ./lisk_service/env/common.env
      - ./lisk_service/env/gateway.env

    healthcheck:
      test: curl --fail http://gateway:9901/api/v1/transactions
