version: "3"
services:

  gateway:
    image: lisk/service_gateway
    networks:
      - services_network
    restart: always
    environment:
      - PORT=9901
      - SERVICE_BROKER=${SERVICE_BROKER}
      - SERVICE_LOG_LEVEL=${SERVICE_LOG_LEVEL}
      - SERVICE_LOG_CONSOLE=${SERVICE_LOG_CONSOLE}
      - SERVICE_LOG_FILE=${SERVICE_LOG_FILE}
      - SERVICE_LOG_GELF=${SERVICE_LOG_GELF}
      - SERVICE_LOG_STDOUT=${SERVICE_LOG_STDOUT}

    healthcheck:
      test: curl --fail http://localhost:9901/api/status
