version: "3"
services:

  core:
    image: lisk/service_core
    depends_on:
      - redis_common
      - redis_core
      - redis_core_volatile
      - mysql_core
    networks:
      - services_network
      - core_network
    restart: always
    environment:
      - LISK_CORE_HTTP=${LISK_CORE_HTTP} # legacy (core2)
      - LISK_CORE_WS=${LISK_CORE_WS}
      - GENESIS_HEIGHT=${GENESIS_HEIGHT}
      - GENESIS_BLOCK_URL=${GENESIS_BLOCK_URL}
      - FEE_EST_DEFAULT_START_BLOCK_HEIGHT=${FEE_EST_DEFAULT_START_BLOCK_HEIGHT}
      - TRANSACTION_STATS_HISTORY_LENGTH_DAYS=${TRANSACTION_STATS_HISTORY_LENGTH_DAYS}
    env_file:
      - ./lisk-service/env/common.env
      - ./lisk-service/env/core.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis_core:
    image: redis:5-alpine
    volumes:
      - ./redis/redis.persistent.conf:/etc/redis/redis.conf:ro
    networks:
      - core_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping

  redis_core_volatile:
    image: redis:5-alpine
    volumes:
      - ./redis/redis.volatile.conf:/etc/redis/redis.conf:ro
    networks:
      - core_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping

  mysql_core:
    image: mysql:5.7
    volumes:
      - mysql_core-data:/var/lib/mysql
    restart: always
    networks:
      - core_network
    env_file:
      - ./lisk-service/env/mysql.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  gateway:
    depends_on:
      - core

volumes:
  mysql_core-data:

networks:
  core_network:
