version: "3"
services:

  market:
    image: lisk/service_market
    depends_on:
      - redis_common
      - redis_market
    networks:
      - services_network
    restart: always
    env_file:
      - ./lisk-service/env/common.env
      - ./lisk-service/env/market.env

  redis_market:
    image: redis:5-alpine
    volumes:
      - ./redis/redis.persistent.conf:/etc/redis/redis.conf:ro
    networks:
      - services_network
    restart: always
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
      