version: '3'
services:
  lisk-core:
    image: lisk/core:3.0.2
    platform: linux/amd64
    volumes:
      - ./snapshots/:/tmp/snapshots
      - ./config/:/tmp/config
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "5001:5001"
    restart: always
    entrypoint: ['sh', '/entrypoint.sh']
    environment:
      - LISK_API_PUBLIC=true
