version: '3'
services:
  lisk-core:
    image: lisk/core:4.0.0-beta.0
    platform: linux/amd64
    volumes:
      - ./snapshots/:/tmp/snapshots
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "7887:7887"
    restart: always
    entrypoint: ['sh', '/entrypoint.sh']
    environment:
      - LISK_API_PUBLIC=true
