= Installation with Docker
Mona Bärenfänger <mona@lightcurve.io> Muhammad Talha <muhammad.talha@lightcurve.io>

:description: Describes all necessary steps and requirements to install Lisk Service with Docker.
:toc:
:experimental:
:page-next: /lisk-service/configuration/docker.html
:page-next-title: Configuration with Docker
:sectnums:

:url_github_service: https://github.com/LiskHQ/lisk-service
:url_docker_hub: https://hub.docker.com/
:url_docker_install_linux: https://docs.docker.com/engine/install
:url_docker_install_linux_compose: https://docs.docker.com/compose/install/
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall/
:url_xcode: https://developer.apple.com/xcode/features/

:lisk-docs: ROOT::
:url_index_usage: index.adoc#usage
:url_setup: setup/index.adoc
:url_core_setup_npm: master@lisk-core::setup/npm.adoc
:url_config: configuration/docker.adoc
:url_management: management/docker.adoc
:url_references_config: configuration/index.adoc
:url_build_blockchain:  {lisk-docs}build-blockchain/create-blockchain-app.adoc

:url_core_setup_binary: master@lisk-core::setup/binary.adoc

How to set up Lisk Service and connect it to a local Lisk Core node.

[NOTE]
====
*Pre-requisite*

Lisk Service is a web application middleware that allows interaction with various blockchain networks based on the Lisk protocol.
It is recommended to set up a blockchain node first, before setting up Lisk Service.

* To set up a Lisk-Core node, see any of our setup guides, such as xref:{url_core_setup_npm}[].
* Alternatively, you can setup up a sidechain node to connect to Lisk Service.
====

// === Setting up Lisk Core

// Lisk Service is installed in addition to a Lisk blockchain application such as Lisk Core, in order to provide enriched network data for third-party services.

// The first step is therefore to install Lisk Core.

// It is recommended to use NPM to conveniently install Lisk Core through the command line:

// [source,bash]
// ----
// npm install --global --production lisk-core
// ----

// Check out the xref:{url_core_setup_npm}[Lisk Core NPM setup] guide for more information on how to install Lisk Core on your machine.

// === Configuring Lisk Core

// Use the Lisk Core CLI to start Lisk Core with the desired configurations.

// * The `--network` flag determines the blockchain network Lisk Core connects to.
// * `--api-ws` enables the WebSocket API of the node, if not already enabled within the config.json file.
// * `--api-ws-host=0.0.0.0` allows remote servers to connect to the Lisk Core WS API.
// If this option is not set, it defaults to `127.0.0.1`.
// * `--api-ws-port=7887` the port for the WebSocket API.

// [source,bash]
// ----
// lisk-core start --network mainnet --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887
// ----

// To connect to a different network, replace `mainnet` with either `testnet` or `devnet`.

== Setting up Lisk Service

[IMPORTANT]
====
It is strongly recommended to synchronize your blockchain node with the network **before** starting the Lisk Service.
====

=== Prerequisites

The following dependencies are required to install and run Lisk Service with Docker.

==== Development tools

[tabs]
====
Ubuntu / Debian::
+
--
Install the `build-essential` package alongside several development tools.

For example, use `apt` if running Ubuntu as shown in the following command below:

[source,bash]
----
apt install build-essential git
----
--
MacOS::
+
--

*Brew*

Install https://brew.sh/[Brew] by following https://brew.sh/[the most recent instruction].

If you already have Brew installed, ensure it is working and is the latest version.

.Update current brew installation
[source,bash]
----
brew update
----

.Verify the brew installation
[source,bash]
----
brew doctor
----

*Xcode*

Install https://developer.apple.com/xcode/[Xcode] essentials coming from Apple.

[source,bash]
----
xcode-select --install
----
--
====

==== Docker & Docker compose

[tabs]
====
Ubuntu / Debian::
+
--
. Please refer to the {url_docker_install_linux}[Docker installation for Ubuntu^].
. To install Docker Compose, please refer to {url_docker_install_linux_compose}[Install Docker Compose^].
. To configure Docker so it can be run without `sudo` rights, follow: {url_docker_linux_post_install}[Linux post install^].
--
MacOS::
+
--
. Please refer to {url_docker_install_mac}[Docker installation for Mac^]. Please note that Docker for Mac already includes Docker Compose.
--
====

==== Open necessary ports

Ensure the port which allows external services communication with the Lisk Service APIs is open.

- The *default* API port for *HTTP* & *WebSocket* is: `9901`

.Example: Opening port 9901 with ufw on Ubuntu
[source,bash]
----
sudo ufw allow 9901
----

=== Installation of Lisk Service

Clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder.

.Execute in the directory where you want to store Lisk Service
[source,bash]
----
git clone https://github.com/LiskHQ/lisk-service.git
cd lisk-service
git checkout v0.7.0
----

== Build Lisk Service

To build Lisk Service from local files, first, navigate to the `lisk-service` repository on your system:

.Working directory: /lisk-service/
[source,bash]
----
make build
----

Lisk Service is now ready to use on your machine.

TIP: If you skipped the step to configure Docker to run without `*sudo*` rights, you need to prepend `*sudo*` with aforementioned command: `*sudo make build*`

== Connecting Lisk Service to a blockchain node

Before running the application copy the default docker-compose environment file:

.Working directory: /lisk-service/
[source,bash]
----
cp docker/example.env .env
----

In the next step, open `.env` to set the required environment variables.

.Working directory: /lisk-service/
[source,bash]
----
vim .env
----


..env
[source,bash]
----
# Lisk ecosystem configuration
LISK_APP_WS=ws://host.docker.internal:7887 
----

The `example.env` assumes that the blockchain node e.g. Lisk Core node is running on the host machine, and not inside of a Docker container.

When running a blockchain node inside of a Docker container, the following variable needs to refer to the container:

..env
[source,bash]
----
# Lisk ecosystem configuration
LISK_APP_WS="ws://<your_docker_container>:7887"
----

TIP: For a complete list of supported environment variables check the xref:{url_references_config}[].

== Starting Lisk Service

Run the following command to start Lisk Service:

.Working directory: /lisk-service/
[source,bash]
----
make up
----

== Stopping Lisk Service
You can stop Lisk Service again with the following command:

.Working directory: /lisk-service/
[source,bash]
----
make down
----

// More commands about how to manage Lisk Service are described on the xref:{url_management}[Docker commands] page.

// TIP: Check the xref:{url_index_usage}[Usage] section for examples of how to use and interact with Lisk Service.
