name: Code Coverage
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: |
          npm ci
          cd ./framework && npm ci
          cd ./services/blockchain-app-registry && npm ci
          cd ./services/blockchain-connector && npm ci
          cd ./services/blockchain-coordinator && npm ci
          cd ./services/blockchain-indexer && npm ci
          cd ./services/transaction-statistics && npm ci
          cd ./services/fee-estimator && npm ci
          cd ./services/market && npm ci
          cd ./services/newsfeed && npm ci
          cd ./services/gateway && npm ci
          cd ./services/export && npm ci
          cd ./services/template && npm ci
          cd ./tests && npm ci
      - name: Check test coverage
        run: npm run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: coverage-final.json
          name: codecov-umbrella
          verbose: true
